version: "3.9"

services:
  api:
    build: .
    container_name: branch_api
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      LOG_LEVEL: ${LOG_LEVEL}
      FLASK_ENV: ${ENV}
    command: >
      sh -c "
        if [ '${API_RELOAD}' = 'true' ];
        then
          flask run --host=0.0.0.0 --port=8000;
        else
          wait-for-postgres db alembic upgrade head &&
          gunicorn wsgi:app -b 0.0.0.0:8000 --workers 4 --timeout 120;
        fi
      "
    volumes:
      - .:/app:cached
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - branchnet

  db:
    image: postgres:14
    container_name: branch_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    mem_limit: ${POSTGRES_MEMORY}
    cpus: ${POSTGRES_CPU}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - branchnet



  nginx:
    image: nginx:alpine
    container_name: branch_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - api
    networks:
      - branchnet

volumes:
  postgres_data:

networks:
  branchnet:
