version: "3.8"

services:
  api:
    build: .
    container_name: branch_api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/branchdb
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
    expose:
      - "8000"
    networks:
      - branchnet

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: branchdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 10
    networks:
      - branchnet


  nginx:
    image: nginx:alpine
    container_name: branch_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - api
    networks:
      - branchnet

volumes:
  postgres_data:

networks:
  branchnet:
